<?php
require_once __DIR__ . '/../config/db.php';
$pageTitle = 'Edit Freelancer | Freelance Marketplace System';
$id=intval($_GET['id']??0); $successMessage=''; $errorMessage=''; if($id<=0){header('Location: freelancers.php?error=Invalid freelancer ID.'); exit;}
$stmt=$conn->prepare("SELECT u.user_id, u.name, u.email, u.password, u.registration_date, f.bio FROM `User` u INNER JOIN Freelancer f ON u.user_id = f.freelancer_id WHERE f.freelancer_id = ?"); $stmt->bind_param('i',$id); $stmt->execute(); $freelancer=$stmt->get_result()->fetch_assoc(); $stmt->close(); if(!$freelancer){header('Location: freelancers.php?error=Freelancer not found.'); exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){ $name=trim($_POST['name']??''); $email=trim($_POST['email']??''); $password=trim($_POST['password']??''); $regDate=trim($_POST['registration_date']??''); $bio=trim($_POST['bio']??''); if($name===''||$email===''||$password===''||$regDate===''){ $errorMessage='Please fill in all required fields.'; } else { $stmt=$conn->prepare("UPDATE `User` SET name = ?, email = ?, password = ?, registration_date = ? WHERE user_id = ?"); $stmt->bind_param('ssssi',$name,$email,$password,$regDate,$id); $ok1=$stmt->execute(); $stmt->close(); $stmt2=$conn->prepare("UPDATE Freelancer SET bio = ? WHERE freelancer_id = ?"); $stmt2->bind_param('si',$bio,$id); $ok2=$stmt2->execute(); $stmt2->close(); if($ok1&&$ok2){$successMessage='Freelancer updated successfully.'; $freelancer=array_merge($freelancer,['name'=>$name,'email'=>$email,'password'=>$password,'registration_date'=>$regDate,'bio'=>$bio]);} else {$errorMessage=($conn->errno===1062)?'This email address is already used by another user.':'Unable to update freelancer.';} } }
include __DIR__ . '/../includes/header.php'; include __DIR__ . '/../includes/navbar.php';
?>
<section class="form-card"><span class="eyebrow">Edit Record</span><h2 class="page-title">Edit Freelancer #<?php echo $id; ?></h2><p class="page-intro">Update the freelancer's information in the User and Freelancer tables.</p><?php if ($successMessage !== ''): ?><div class="message success"><?php echo htmlspecialchars($successMessage); ?></div><?php endif; ?><?php if ($errorMessage !== ''): ?><div class="message error"><?php echo htmlspecialchars($errorMessage); ?></div><?php endif; ?><form method="POST" action=""><div class="form-row"><div><label for="name">Full Name *</label><input type="text" id="name" name="name" required value="<?php echo htmlspecialchars($freelancer['name']); ?>"></div><div><label for="email">Email Address *</label><input type="email" id="email" name="email" required value="<?php echo htmlspecialchars($freelancer['email']); ?>"></div></div><div class="form-row"><div><label for="password">Password *</label><input type="text" id="password" name="password" required value="<?php echo htmlspecialchars($freelancer['password']); ?>"></div><div><label for="registration_date">Registration Date *</label><input type="date" id="registration_date" name="registration_date" required value="<?php echo htmlspecialchars($freelancer['registration_date']); ?>"></div></div><div><label for="bio">Bio</label><textarea id="bio" name="bio"><?php echo htmlspecialchars($freelancer['bio'] ?? ''); ?></textarea></div><div class="form-actions"><button type="submit">Update Freelancer</button><a class="btn btn-secondary" href="<?php echo $basePath; ?>/pages/freelancers.php">Cancel</a></div></form></section>
<?php include __DIR__ . '/../includes/footer.php'; $conn->close(); ?>