<?php
require_once __DIR__ . '/../config/db.php';
$pageTitle = 'Freelancers | Freelance Marketplace System';
$search = trim($_GET['search'] ?? ''); $successMsg = $_GET['success'] ?? ''; $errorMsg = $_GET['error'] ?? '';
$query = "SELECT f.freelancer_id, u.name, u.email, u.registration_date, f.bio FROM Freelancer f INNER JOIN `User` u ON f.freelancer_id = u.user_id";
if ($search !== '') { $query .= " WHERE u.name LIKE ? OR u.email LIKE ? OR f.bio LIKE ?"; }
$query .= " ORDER BY f.freelancer_id";
if ($search !== '') { $stmt=$conn->prepare($query); $like='%'.$search.'%'; $stmt->bind_param('sss',$like,$like,$like); $stmt->execute(); $freelancers=$stmt->get_result(); } else { $freelancers=$conn->query($query); }
include __DIR__ . '/../includes/header.php'; include __DIR__ . '/../includes/navbar.php';
?>
<section class="table-card"><div class="section-heading"><div><span class="eyebrow">Freelancer Records</span><h2 class="page-title">Freelancers</h2><p class="page-intro">All registered freelancers with their biographies.</p></div><div class="section-actions"><a class="btn" href="<?php echo $basePath; ?>/pages/add_freelancer.php">+ Add Freelancer</a></div></div><?php if ($successMsg !== ''): ?><div class="message success"><?php echo htmlspecialchars($successMsg); ?></div><?php endif; ?><?php if ($errorMsg !== ''): ?><div class="message error"><?php echo htmlspecialchars($errorMsg); ?></div><?php endif; ?><form method="GET" action="" class="search-bar" style="display:flex;"><input type="text" name="search" placeholder="Search by name, email, or bio..." value="<?php echo htmlspecialchars($search); ?>"><button type="submit" class="btn btn-secondary">Search</button><?php if ($search !== ''): ?><a href="<?php echo $basePath; ?>/pages/freelancers.php" class="btn btn-secondary">Clear</a><?php endif; ?></form><div class="table-wrapper"><table class="data-table freelancers-table"><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Registration Date</th><th>Bio</th><th>Actions</th></tr></thead><tbody><?php if ($freelancers && $freelancers->num_rows > 0): ?><?php while ($row = $freelancers->fetch_assoc()): ?><tr><td class="col-id"><?php echo $row['freelancer_id']; ?></td><td class="col-name"><?php echo htmlspecialchars($row['name']); ?></td><td class="col-email"><?php echo htmlspecialchars($row['email']); ?></td><td class="col-date"><?php echo htmlspecialchars($row['registration_date']); ?></td><td class="col-description"><?php echo htmlspecialchars($row['bio'] ?? ''); ?></td><td class="col-actions"><div class="btn-group"><a class="btn btn-sm btn-secondary" href="<?php echo $basePath; ?>/pages/edit_freelancer.php?id=<?php echo $row['freelancer_id']; ?>">Edit</a><a class="btn btn-sm btn-danger" href="<?php echo $basePath; ?>/pages/delete_freelancer.php?id=<?php echo $row['freelancer_id']; ?>" onclick="return confirm('Are you sure you want to delete this freelancer?');">Delete</a></div></td></tr><?php endwhile; ?><?php else: ?><tr><td colspan="6"><div class="empty-state"><p>No freelancers found.</p><a class="btn" href="<?php echo $basePath; ?>/pages/add_freelancer.php">Add the first freelancer</a></div></td></tr><?php endif; ?></tbody></table></div></section>
<?php include __DIR__ . '/../includes/footer.php'; $conn->close(); ?>
