<?php
require_once __DIR__ . '/../config/db.php';
$pageTitle = 'Project Details | Freelance Marketplace System';
$projectId=intval($_GET['project_id']??0); if($projectId<=0){header('Location: projects.php?error=Invalid project ID.'); exit;}
$stmt=$conn->prepare("SELECT p.*, u.name AS client_name FROM Project p INNER JOIN Client c ON p.client_id=c.client_id INNER JOIN `User` u ON c.client_id=u.user_id WHERE p.project_id=?"); $stmt->bind_param('i',$projectId); $stmt->execute(); $project=$stmt->get_result()->fetch_assoc(); $stmt->close(); if(!$project){header('Location: projects.php?error=Project not found.'); exit;}
$propStmt=$conn->prepare("SELECT pr.proposal_id, pr.cover_letter, pr.bid_amount, pr.date_submitted, pr.status, pr.freelancer_id, u.name AS freelancer_name FROM Proposal pr INNER JOIN Freelancer f ON pr.freelancer_id=f.freelancer_id INNER JOIN `User` u ON f.freelancer_id=u.user_id WHERE pr.project_id=? ORDER BY pr.proposal_id"); $propStmt->bind_param('i',$projectId); $propStmt->execute(); $proposals=$propStmt->get_result(); $propStmt->close();
$contractStmt=$conn->prepare("SELECT ct.contract_id, ct.start_date, ct.end_date, ct.status, ct.proposal_id FROM Contract ct INNER JOIN Proposal pr ON ct.proposal_id=pr.proposal_id WHERE pr.project_id=?"); $contractStmt->bind_param('i',$projectId); $contractStmt->execute(); $contracts=$contractStmt->get_result(); $contractStmt->close();
include __DIR__ . '/../includes/header.php'; include __DIR__ . '/../includes/navbar.php';
?>
<section class="table-card" style="margin-bottom:24px;"><div class="section-heading"><div><span class="eyebrow">Project #<?php echo $project['project_id']; ?></span><h2 class="page-title"><?php echo htmlspecialchars($project['title']); ?></h2></div><div class="section-actions"><a class="btn btn-secondary" href="<?php echo $basePath; ?>/pages/projects.php">&larr; Back to Projects</a><a class="btn btn-secondary" href="<?php echo $basePath; ?>/pages/edit_project.php?id=<?php echo $project['project_id']; ?>">Edit</a></div></div><div class="detail-list"><div class="detail-item"><span class="detail-label">Project ID</span><span class="detail-value"><?php echo $project['project_id']; ?></span></div><div class="detail-item"><span class="detail-label">Budget</span><span class="detail-value">$<?php echo number_format((float)$project['budget'],2); ?></span></div><div class="detail-item"><span class="detail-label">Status</span><span class="badge badge-<?php echo strtolower(str_replace(' ','',$project['status'])); ?>"><?php echo htmlspecialchars($project['status']); ?></span></div><div class="detail-item"><span class="detail-label">Date Posted</span><span class="detail-value"><?php echo htmlspecialchars($project['date_posted']); ?></span></div><div class="detail-item"><span class="detail-label">Client</span><span class="detail-value"><?php echo htmlspecialchars($project['client_name']); ?> (ID: <?php echo $project['client_id']; ?>)</span></div></div><?php if(!empty($project['description'])):?><div class="description-box"><h3>Description</h3><p><?php echo nl2br(htmlspecialchars($project['description'])); ?></p></div><?php endif;?></section>
<div class="two-column"><section class="table-card"><h3 class="page-title" style="font-size:1.3rem;">Proposals for This Project</h3><p class="page-intro">All proposals submitted by freelancers for this project.</p><div class="table-wrapper"><table><thead><tr><th>ID</th><th>Freelancer</th><th>Bid Amount</th><th>Status</th><th>Date</th><th>Cover Letter</th></tr></thead><tbody><?php if($proposals&&$proposals->num_rows>0): while($prop=$proposals->fetch_assoc()):?><tr><td><?php echo $prop['proposal_id']; ?></td><td><?php echo htmlspecialchars($prop['freelancer_name']); ?> (ID: <?php echo $prop['freelancer_id']; ?>)</td><td>$<?php echo number_format((float)$prop['bid_amount'],2); ?></td><td><span class="badge badge-<?php echo strtolower($prop['status']); ?>"><?php echo htmlspecialchars($prop['status']); ?></span></td><td><?php echo htmlspecialchars($prop['date_submitted']); ?></td><td><?php echo htmlspecialchars($prop['cover_letter'] ?? ''); ?></td></tr><?php endwhile; else:?><tr><td colspan="6"><div class="empty-state"><p>No proposals for this project yet.</p></div></td></tr><?php endif;?></tbody></table></div></section><section class="table-card"><h3 class="page-title" style="font-size:1.3rem;">Contracts</h3><p class="page-intro">Contracts created from accepted proposals on this project.</p><div class="table-wrapper"><table><thead><tr><th>Contract ID</th><th>Proposal ID</th><th>Start Date</th><th>End Date</th><th>Status</th></tr></thead><tbody><?php if($contracts&&$contracts->num_rows>0): while($ct=$contracts->fetch_assoc()):?><tr><td><?php echo $ct['contract_id']; ?></td><td><?php echo $ct['proposal_id']; ?></td><td><?php echo htmlspecialchars($ct['start_date']); ?></td><td><?php echo $ct['end_date']?htmlspecialchars($ct['end_date']):'Not set'; ?></td><td><span class="badge badge-<?php echo strtolower($ct['status']); ?>"><?php echo htmlspecialchars($ct['status']); ?></span></td></tr><?php endwhile; else:?><tr><td colspan="5"><div class="empty-state"><p>No contracts for this project yet.</p></div></td></tr><?php endif;?></tbody></table></div></section></div>
<section class="section-card" style="padding:28px; margin-top:24px;"><h3 class="page-title" style="font-size:1.3rem;">Relationship Visualization</h3><p class="page-intro">This diagram shows how the Client, Project, Proposal, and Contract entities are related for this project.</p><div class="relationship-box"><div class="relationship-node"><span>Client</span><strong><?php echo htmlspecialchars($project['client_name']); ?></strong></div><div class="relationship-arrow">&rarr;</div><div class="relationship-node"><span>Project</span><strong><?php echo htmlspecialchars($project['title']); ?></strong></div></div></section>
<?php include __DIR__ . '/../includes/footer.php'; $conn->close(); ?>
